minimumReleaseAgeExclude:
  - '@rozie-ui/combobox-solid@0.6.0 || 0.7.0'
  - '@rozie-ui/command-palette-solid@0.4.10 || 0.5.0'
  - '@rozie-ui/data-table-solid@0.6.0 || 0.7.0 || 0.7.1'
  - '@rozie-ui/popover-solid@0.2.4 || 0.3.0'
  - '@rozie-ui/tags-solid@0.1.10 || 0.1.11'
  - '@rozie-ui/tiptap-solid@0.4.0 || 0.5.0 || 0.5.1'
  - '@rozie-ui/toast-solid@0.2.0 || 0.2.1 || 0.2.2'
  - '@rozie/runtime-keynav-core@0.7.5 || 0.8.0'
  - '@rozie/runtime-solid@0.7.5 || 0.8.0'
  - '@rozie-ui/dialog-solid@0.1.3 || 0.2.0'
  - '@rozie-ui/fullcalendar-solid@0.2.0'
